### ISSUE TITLE
incompatibility with loader 0.15+

### ISSUE THREAD

**Issue by tildejustin** [Sjouwer/OptiFabric-1.14.4-Updated#3]
with the change to mapping-io and the repackaging and updates to tiny-remapper, there are some changes that need to be made for loader 0.15+ compatibility

**Comment by Sjouwer** [comment]
Thank you for the report.
I'm not very familiar with the remapper.
I'll try and figure that out when I got some spare time, though not sure when that'll be.
If you're familiar with it and are willing to help out, please feel free to make a PR, that would be very much appreciated

**Comment by tildejustin** [comment]
done 👍 i worry about the stability of using loader internals in the long term but switching to self-packaged versions is a massive headache since you have to somehow load all the classes from tiny-remapper ahead of time to stop the mixin classloader from deadlocking? it's a mess :P

**Comment by Sjouwer** [comment]
Thanks a lot!
Tested it out, and so far seems to work great.
Did have to change 1 line to get it working, though that might be because I'm using an older Java version than you.

I agree about the use of the loader internals, though it's probably not worth the trouble to go with the self packaged route
